// <auto-generated />
using System;
using Kind.Systems.Rates.WebApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kind.Systems.Rates.WebApp.Infrastructure.Kind.Systems.Rates.WebApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250628110457_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Kind.Systems.Rates.WebApp.Domain.Models.ExchangeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RetrievedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RetrievedAt");

                    b.ToTable("Rates");
                });

            modelBuilder.Entity("Kind.Systems.Rates.WebApp.Domain.Models.ExchangeRate", b =>
                {
                    b.OwnsOne("Kind.Systems.Rates.WebApp.Domain.Models.CurrencyPair", "Pair", b1 =>
                        {
                            b1.Property<Guid>("ExchangeRateId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Base")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Base");

                            b1.Property<string>("Quote")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Quote");

                            b1.HasKey("ExchangeRateId");

                            b1.HasIndex("Base", "Quote");

                            b1.ToTable("Rates");

                            b1.WithOwner()
                                .HasForeignKey("ExchangeRateId");
                        });

                    b.Navigation("Pair")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
